### ISSUE TITLE
Hover Animated Buttons

### ISSUE THREAD

**Issue by bibhanshu01** [aniketsinha2002/DataGeek#655]
### Description

The buttons will show animation effect on hover.

As a GSSoC Contributor, I want to add this feature of animation effect on buttons.
Kindly assign me this.

**Comment by ZainabR11** [comment]
I can enhance project with captivating Hover Animated Buttons. My CSS animation skills will elevate our user interface. Assign me this task for an engaging user experience.

**Comment by ZainabR11** [comment]
Thankyou for assigning.

**Comment by ZainabR11** [comment]
@aniketsinha2002  I have completed my task of animated hover effect on button. But I am facing some issues in using github to push my code. It is my first time. Kindly guide me.

**Comment by aniketsinha2002** [comment]
@ZainabR11 Sure!! What exact issue are you facing ?

**Comment by ZainabR11** [comment]
I have cloned it and made some changes inside code , I have also created branch name as hack1 but what I have to do next? From: Aniket SinhaSent: Tuesday, 3 October 2023 7:29 pmTo: aniketsinha2002/DataScienceWebsite.github.ioCc: ZainabR11; MentionSubject: Re: [aniketsinha2002/DataScienceWebsite.github.io] Hover Animated Buttons (Issue ***@***.*** Sure!! What exact issue are you facing ?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by ZainabR11** [comment]
@aniketsinha2002 I have send you an email.

**Comment by krishnagitcontri** [comment]
is this issue still open please assign me!!!

**Comment by krishnagitcontri** [comment]
@aniketsinha2002 Please give the repo file and src where you want to add hover button.
