### ISSUE TITLE
The font of "Frequently asked questions" section is too big and the "Contact us" page does not have the navbar

### ISSUE THREAD

**Issue by ritikalath30** [aniketsinha2002/DataGeek#699]
### Description

The font size of the "Frequently Asked Questions" Section is too large, making the UI not appealing, and the "Contact Us" page should have a navbar in case the user wishes to get back to the home page. 
I would like to make the above-mentioned changes in the code.

### Screenshots

![image](https://github.com/aniketsinha2002/DataScienceWebsite.github.io/assets/64362328/54745e2f-6a8c-4f65-9158-8b79c077b039)

![image](https://github.com/aniketsinha2002/DataScienceWebsite.github.io/assets/64362328/4a2cf6fa-bef9-4f59-8662-6518d23c1967)

**Comment by ritikalath30** [comment]
@aniketsinha2002 kindly assign me this issue.

**Comment by ritikalath30** [comment]
Permission to aniketsinha2002/DataScienceWebsite.github.io.git denied to ritikalath30.
fatal: unable to access 'https://github.com/aniketsinha2002/DataScienceWebsite.github.io.git/': The requested URL returned error: 403

@aniketsinha2002 could you help me out with this.

**Comment by Chawlaradhika** [comment]
@aniketsinha2002 Hi, I'd like to work on this issue if it is'nt fixed yet

**Comment by TusharDahiyaa** [comment]
@aniketsinha2002 Hey, I'd like to work in this. I think this issue is still open and the font-size is still bigger in FAQs section but the contact page does have a navbar now but the contact text and the icons have a lot of white space between them.

Could you assign this to me if this is still open?

**Comment by aniketsinha2002** [comment]
@TusharDahiyaa Assigned!

**Comment by TusharDahiyaa** [comment]
@aniketsinha2002  Updated the code for the fixes. Please check and merge.

**Comment by aniketsinha2002** [comment]
@TusharDahiyaa , there are many bugs. Redirect links are totally wrong. Also, clicking on the contact page redirects to a new index.html file, which shouldn't be there. Additionally, the header is getting changed when clicking on the contact section.

Next time, while creating a PR, screen record the changes you have made with a small video demonstrating the modifications

**Comment by TusharDahiyaa** [comment]
@aniketsinha2002 I did check the code and I get the problem about contact navbar and main navbar being different because they are two separate index.html files already. I didn't make the separate redirects. And right now the site logo of "DATA SCIENCE" is redirecting to a random page from Team page and redirecting to [127.0.0.1/index.html] from contact page. I changed these redirects only to go to "/" root directory as hosted on GitHub. I will rechange the code for navbar look and also include the video . I also attached a current issue video on live site.

https://github.com/aniketsinha2002/DataGeek/assets/66515549/f6cd1bfa-6267-40de-890b-9d988f526a3c

**Comment by TusharDahiyaa** [comment]
@aniketsinha2002 I did check the code and I get the problem about contact navbar and main navbar being different because they are two separate index.html files already. I didn't make the separate redirects. And right now the site logo of "DATA SCIENCE" is redirecting to a random page from Team page and redirecting to [127.0.0.1/index.html] from contact page. I changed these redirects only to go to "/" root directory as hosted on GitHub. I will rechange the code for navbar look and also include the video . I also attached a current issue video on live site.


https://github.com/aniketsinha2002/DataGeek/assets/66515549/fa4e95fb-b1e2-4741-8997-e9aa95df4e16

**Comment by aniketsinha2002** [comment]
@TusharDahiyaa Exactly that's the issue I'm talking about, which you have shown in the video. Can you fix this ?

**Comment by TusharDahiyaa** [comment]
@aniketsinha2002 I can definitely try my best. However, one thing, the contact index.html and team index.html are already different index files in the folder structure, so it has to redirect to new index.html or contact.html  or team.html respectively if I change the file names. What do you think I should do for this case?

**Comment by aniketsinha2002** [comment]
@TusharDahiyaa  Keep the files as they are. Just work on fixing the header and logo parts. They should look the same on all pages, including Home, About, Courses, FAQ, Contact, and Team.

For example, on the Contact page, the Team tab is missing. In conclusion, the same header must be present on all pages.

**Comment by TusharDahiyaa** [comment]
@aniketsinha2002 Updated the code for the above mentioned issues. I have attached a video recording in the PR for your reference. Please check and merge.

**Comment by TusharDahiyaa** [comment]
@aniketsinha2002 It's done. Created a new pull request which has no conflicts and same resolved code. Please check and merge.
